name: for_learn
description: Учебный репозиторий для домашних заданий по Dart/Flutter и Git
version: 0.1.0

environment:
  sdk: '^3.0.0'

dependencies:
# сюда при необходимости добавишь пакеты

dev_dependencies:
  lints: ^3.0.0
