name: task02
description: A Flutter project for HTTP requests and JSON serialization
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Добавил эти зависимости:
  http: ^1.2.0
  path: ^1.9.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Добавил эти dev-зависимости:
  build_runner: ^2.4.8
  json_serializable: ^6.11.3

flutter:
  uses-material-design: true